version: '3.8'

services:
  bot:
    build: .
    container_name: trading_bot
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: trading_db
    restart: always
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: securepass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: